# This is how Jekyll knows to use this theme.
theme: jekyll-sleek

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Strona główna', link: '/'}
  - {name: 'O mnie', link: '/about'}
  - {name: 'Kontakt', link: '/contact'}

title: Portfolio
author: Jacek Blady
email: jacek.bldy@gmail.com
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
hero_img: wallpaper4.png


# Header Links - all optional. If set these create header links.
github_username: jacekbla
linkedin_username: jacek-blady


plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-remote-theme # Lets us test remote themes locally.