# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Strona główna', link: '/'}
  - {name: 'O mnie', link: '/about'}
  - {name: 'Kontakt', link: '/contact'}
  - {name: 'ENG', link: '/eng'}
  - {name: 'Home', link: '/eng'}
  - {name: 'About me', link: '/eng/about'}
  - {name: 'Contact', link: '/eng/contact'}
  - {name: 'PL', link: '/'}

# SITE CONFIGURATION
title: Jacek Blady
author: Jacek Blady
email: jacek.bldy@gmail.com
description: >
  Portfolio
hero_img: wallpaper4.png
#url: "https://jacekbla.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

tagline: >
  Portfolio

# SEO PLUGIN
social:
  name: Jacek Blady
  links:
    - https://www.facebook.com/jacek.blady.9
    - https://www.linkedin.com/in/jacek-blady-47718a118/
    - https://github.com/jacekbla
    - https://bitbucket.org/jacekbla

# Header Links - all optional. If set these create header links.
github_username: jacekbla
linkedin_username: jacek-blady
bitbucket_username: jacekbla

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
